import type { Metadata } from "next";
import "./globals.css";
import {cn} from "@/lib/utils";
import { Inter } from "next/font/google"
import AppBar from "@/app/components/AppBar";

const fontHeading = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
          className={cn(
              'antialiased',
              fontHeading.variable,
              fontBody.variable
          )}
      >
      <AppBar/>
      {children}
      </body>
      </html>
  );
}
